### ISSUE TITLE
Function To convert hexa-decimals to any base system

### ISSUE THREAD

**Issue by RotimiFreq** [AltGophers/numbase#14]
I want to refactor the code in the hexTOoct function to call the anybase to anybase function.

**Comment by emmrys-jay** [comment]
Alright, Its been assigned to you. You can join the community here t.me/+gKyUH8L50vYwODg0

**Comment by emmrys-jay** [comment]
PR merged, you can close this issue.

**Comment by RotimiFreq** [comment]
Okayy. Can you explain how you fixed the conflict?

**Comment by emmrys-jay** [comment]
There was a "Resolve Conflict" button which leads to where one can edit a file containing a combination of files from both repos causing the conflict. You can check out a brief youtube video to see how it works.

**Comment by RotimiFreq** [comment]
Thanks, I'll check it out.
