### ISSUE TITLE
Convert numbers from specified bases (less than base 10) to desired bases (less than base 10)

### ISSUE THREAD

**Issue by meshachdamilare** [AltGophers/numbase#6]
## Description
Implement a function that allows conversion of numbers from any base less than base 10 to any desired base less than 10

## What features will you implement? (an exhaustive list)
- Create a function to convert from specified bases  to desired bases (all less than base 10)
- Use the toBase10 function for easy implamentation
- Error Handling

**Comment by emmrys-jay** [comment]
@Christomesh you can close this issue since it's been merged.
