### ISSUE TITLE
Create a simple webserver that will serve HTML(webpage that will take input) through a localhost

### ISSUE THREAD

**Issue by ayoweb3** [AltGophers/numbase#9]
### Description
Create a webserver that will help in serving a webpage through a localhost port e.g http://localhost:8080

###What features will you implement? (an exhaustive list)

- create a webserver that will serve a webpage through a localhost
- create a usable webpage that will take input for the conversion to the desired bases
- Add little styling (css) to the webpage
- print the result of the base conversion on the webpage

**Comment by emmrys-jay** [comment]
The issue has been assigned to you @realisijola

**Comment by ayoweb3** [comment]
thank you

**Comment by emmrys-jay** [comment]
@realisijola PR has been merged, you can close this issue
